services:
  cowrie:
    image: cowrie/cowrie:latest
    restart: unless-stopped
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./cowrie/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      # Ajoutons des points de montage spécifiques pour les deux chemins possibles
      - ./cowrie/log:/cowrie/cowrie-git/var/log:rw
      - ./cowrie/log/cowrie:/cowrie/cowrie-git/var/log/cowrie:rw
      - ./cowrie/keys:/home/cowrie/keys:ro
      - ./cowrie/data/rootfs:/home/cowrie/data/rootfs:ro
      - ./cowrie/etc/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt:ro

  mongo:
    image: mongo:5
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  ingestion:
    build: ./ingestion
    restart: unless-stopped
    depends_on:
      - cowrie
      - mongo
    volumes:
      # Montons également le dossier parent pour couvrir les deux possibilités
      - ./cowrie/log:/cowrie/cowrie-git/var/log:ro
      - ./cowrie/log/cowrie:/cowrie/cowrie-git/var/log/cowrie:ro

  dashboard:
    build: ./dashboard
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - mongo
      - ingestion
    volumes:
      - ./dashboard/GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb:ro

volumes:
  mongo_data:
